name: musictobeligth
description: "A música é o instrumento. O objetivo é ser luz"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  audioplayers: ^5.2.1
  dio: ^5.4.0
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  validatorless: ^1.2.3
  intl: ^0.19.0
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
