name: Json Rest Server
port: 8080
host: 10.90.13.228
database: database.json

# auth:
#   jwtSecret: cwsMXDtuP447WZQ63nM4dWZ3RppyMl
#   jwtExpire: 3600
#   unauthorizedStatusCode: 403
#   urlSkip:
#     - /images/:
#        method: get
#     - /users:
#        method: post
#      - /products/{*}:
#        method: get
